// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrTlWdvzOZQRVJsde8QvAY4R-1inSM62Y',
    appId: '1:937477696944:web:bdea5fd5cb04a8821eba75',
    messagingSenderId: '937477696944',
    projectId: 'lifegoalspdm',
    authDomain: 'lifegoalspdm.firebaseapp.com',
    storageBucket: 'lifegoalspdm.appspot.com',
    measurementId: 'G-QPCTTKR4BX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoDT6KDPFXDYqd_yXgnYc5K1DOmDrwFjI',
    appId: '1:937477696944:android:1a4ff3cc612926d51eba75',
    messagingSenderId: '937477696944',
    projectId: 'lifegoalspdm',
    storageBucket: 'lifegoalspdm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWZR16vWBmq_6rZSfMisjajdAHz9mNIRg',
    appId: '1:937477696944:ios:8b7b6c678d0a633f1eba75',
    messagingSenderId: '937477696944',
    projectId: 'lifegoalspdm',
    storageBucket: 'lifegoalspdm.appspot.com',
    iosClientId: '937477696944-o4n7d5te68mf1ekfulkj66clvu0mdg2c.apps.googleusercontent.com',
    iosBundleId: 's',
  );
}
